---
author: "Stéphane R. Richard"
email: "blog@zanshine.com"
title: "jekyll or hide"
subtitle: "A basic project for the jekyll blog generator"
url: "https://github.com/zanshine/jekyll-base-project"
description: ""
short_description: "Stéphane R. Richard's website, cg artworks, music and software development"

theme:          plain
permalink:      /blog/stephane-richard/:categories/:year-:month-:day/:title
